[package]
edition = "2024"
name    = "raft"
version = "0.1.0"

[lib]
name = "raft"
path = "lib.rs"

[dependencies]
async-trait  = { workspace = true }
bytes = "1.10.1"
futures-util = "0.3.31"
tokio        = { version = "1.47.1", features = ["full"] }
